import axios from "axios"
import Head from "next/head"
import Image from "next/image"
import { useAsync } from "../hooks/use-async"
import styles from "../styles/Home.module.css"
import { Layout } from "../components/layout"

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>Home Page :)</Layout>
      {/* footer */}
    </>
  )
}
