# This file contains values from Cookiecutter

default_context:
  project_name: "notion_renderer"
  project_description: "Awesome `notion_renderer` is a Python cli/package created with https://github.com/TezRomacH/python-package-template"
  organization: "notion_renderer"
  license: "MIT"
  minimal_python_version: 3.5
  github_name: "notion_renderer"
  email: "ruucm.a@gmail.com"
  version: "0.1.0"
  line_length: "88"
  create_example_template: "cli"
